# Generated by Django 4.2.3 on 2023-07-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
