# Generated by Django 4.2.3 on 2023-07-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0006_rename_user_orderhistory_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='customer',
            new_name='user',
        ),
    ]
