# Generated by Django 4.2.3 on 2023-07-26 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0007_rename_customer_orderhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuci_mobil.customer'),
            preserve_default=False,
        ),
    ]
