# Generated by Django 4.2.3 on 2023-07-26 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0008_remove_orderhistory_user_orderhistory_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='vehicle',
            new_name='pick',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='plat_nomor',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='tanggal_cuci',
            field=models.DateField(default=datetime.datetime(2023, 7, 26, 7, 12, 27, 662327, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
    ]
