# Generated by Django 4.2.3 on 2023-08-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0009_rename_vehicle_customer_pick_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
