# Generated by Django 4.2.3 on 2023-08-10 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuci_mobil', '0013_remove_lapak_tipe_lapak_lapak_harga_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapak',
            name='harga_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lapak',
            name='harga_min',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
