# Generated by Django 4.2.3 on 2023-08-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0016_remove_payment_order_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pick',
            new_name='kendaraan',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='nomor_telepon',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='confirmed',
            new_name='konfirmasi',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='tanggal_order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_time',
            new_name='waktu_order',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='date_ordered',
            new_name='tanggal_order',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='tanggal_bayar',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='foto_profil',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='nama_lengkap',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='tanggal_lahir',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tanggal_cuci',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
    ]
