# Generated by Django 4.2.3 on 2023-08-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0017_rename_pick_customer_kendaraan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='alamat',
        ),
    ]
