# Generated by Django 4.2.3 on 2023-08-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0020_alter_lapak_kategori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tanggal_order',
            new_name='tanggal_cuci',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='kendaraan',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nomor_telepon',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='plat_nomor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waktu_order',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kategori_kendaraan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nomor_telepon',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='plat_nomor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waktu_pengerjaan',
            field=models.TimeField(null=True),
        ),
    ]
