# Generated by Django 4.2.3 on 2023-08-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0021_rename_tanggal_order_order_tanggal_cuci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
