# Generated by Django 4.2.3 on 2023-08-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0024_rename_nama_service_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
    ]
