# Generated by Django 4.2.3 on 2023-08-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0025_remove_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapak',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuci_mobil.service'),
        ),
    ]
