# Generated by Django 4.2.3 on 2023-09-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0030_alter_chat_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lapak',
            old_name='harga_max',
            new_name='harga_mobil',
        ),
        migrations.RenameField(
            model_name='lapak',
            old_name='harga_min',
            new_name='harga_motor',
        ),
    ]
