# Generated by Django 4.2.3 on 2023-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0011_rename_username_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lapak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='lapak_photos/')),
                ('nama_lapak', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('Khusus Mobil', 'Khusus Mobil'), ('Khusus Motor', 'Khusus Motor'), ('Campur', 'Campur')], max_length=50)),
                ('tipe_lapak', models.CharField(choices=[('Lapak Sendiri', 'Lapak Sendiri'), ('Lapak Orang Lain', 'Lapak Orang Lain')], max_length=20)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
