# Generated by Django 4.2.3 on 2023-08-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0012_lapak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapak',
            name='tipe_lapak',
        ),
        migrations.AddField(
            model_name='lapak',
            name='harga_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lapak',
            name='harga_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
