# Generated by Django 4.2.3 on 2023-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0018_rename_address_profile_alamat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapak',
            name='kategori',
            field=models.CharField(choices=[('Khusus Mobil', 'Khusus Mobil'), ('Khusus Motor', 'Khusus Motor'), ('Mobil  dan Motor', 'Mobil dan Motor')], max_length=50),
        ),
    ]
