# Generated by Django 4.2.3 on 2023-09-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0029_alter_message_options_remove_message_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', to='cuci_mobil.customer'),
        ),
    ]
