# Generated by Django 4.2.3 on 2023-09-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0031_rename_harga_max_lapak_harga_mobil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
