# Generated by Django 4.2.3 on 2023-09-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0033_customer_is_active_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
    ]
