# Generated by Django 4.2.3 on 2023-09-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0039_remove_customer_groups_remove_customer_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_permissions',
        ),
    ]
