# Generated by Django 4.2.3 on 2023-11-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0041_remove_service_deskripsi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lapak',
            old_name='harga_mobil',
            new_name='harga',
        ),
        migrations.RemoveField(
            model_name='lapak',
            name='harga_motor',
        ),
        migrations.AlterField(
            model_name='lapak',
            name='kategori',
            field=models.CharField(choices=[('Khusus Mobil', 'Khusus Mobil')], max_length=50),
        ),
    ]
