# Generated by Django 4.2.3 on 2023-11-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuci_mobil', '0042_rename_harga_mobil_lapak_harga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapak',
            name='kategori',
            field=models.CharField(choices=[('Cuci Mobil', 'Cuci Mobil')], max_length=50),
        ),
    ]
